dotenv: .env

networks:
  # The default network is development, so there is no need to include it
  # unless we want to change it
  default: development
  rinkeby:
    verify: True
  development:
    verify: False
  ganache-rp:
    verify: False

wallets:
  from_key: ${PRIVATE_KEY}
